"""Vendor-neutral domain models for WarpBuster Core."""

from warpbuster.models.activity import (
    ActivityData,
    ActivityRecord,
    CoordinateBounds,
    DeveloperFieldDefinition,
    FitPreservationData,
    SourceMessage,
    SourceRecordRef,
    UnknownFieldSummary,
)
from warpbuster.models.integrity import (
    BaselineStats,
    BridgeCandidateDiagnostic,
    BridgeCandidateOutcome,
    BridgeResult,
    CorruptedInterval,
    IntegrityConfidence,
    IntegrityReport,
    IntegrityStatus,
    IntervalReason,
    IslandSearchDiagnostics,
    TransitionClassification,
    TransitionReason,
    TransitionResult,
)

__all__ = [
    "ActivityData",
    "ActivityRecord",
    "BaselineStats",
    "BridgeCandidateDiagnostic",
    "BridgeCandidateOutcome",
    "BridgeResult",
    "CoordinateBounds",
    "CorruptedInterval",
    "DeveloperFieldDefinition",
    "FitPreservationData",
    "IntegrityConfidence",
    "IntegrityReport",
    "IntegrityStatus",
    "IntervalReason",
    "IslandSearchDiagnostics",
    "SourceMessage",
    "SourceRecordRef",
    "TransitionClassification",
    "TransitionReason",
    "TransitionResult",
    "UnknownFieldSummary",
]
